/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/assets/models/circle2.glb -t -o src/components/Circle2.tsx
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Circle002_1: THREE.Mesh;
    Circle002_2: THREE.Mesh;
  };
  materials: {
    Outer: THREE.MeshStandardMaterial;
    Base: THREE.MeshStandardMaterial;
  };
};

export function CircleModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/assets/models/circle2.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle002_1.geometry} material={materials.Outer} />
      <mesh geometry={nodes.Circle002_2.geometry} material={materials.Base} />
    </group>
  );
}

useGLTF.preload("/assets/models/circle2.glb");
